CREATE TABLE `businesskeys` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `BUSINESS_KEY` varchar(255) DEFAULT NULL,
  `BUSINESS_KEY_TYPE` varchar(255) DEFAULT NULL,
  `TIMESTAMP` bigint(20) DEFAULT NULL,
  `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_businessKey` (`BUSINESS_KEY`),
  KEY `idx_workflowInstanceKey` (`WORKFLOW_INSTANCE_KEY`),
  KEY `idx_businessKeyType` (`BUSINESS_KEY_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `tasks` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ELEMENT_ID` varchar(255) DEFAULT NULL,
  `INTENT` varchar(255) DEFAULT NULL,
  `RECORD_TYPE` varchar(255) DEFAULT NULL,
  `TIMESTAMP` bigint(20) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
  `WORKFLOW_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_tasks_key` (`WORKFLOW_INSTANCE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `transfers` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AMOUNT` decimal(38,0) DEFAULT NULL,
  `CURRENCY` varchar(255) DEFAULT NULL,
  `COMPLETED_AT` datetime DEFAULT NULL,
  `DIRECTION` varchar(10) DEFAULT NULL,
  `PAYEE_DFSP_ID` varchar(255) DEFAULT NULL,
  `PAYEE_FEE` decimal(38,0) DEFAULT NULL,
  `PAYEE_FEE_CURRENCY` varchar(255) DEFAULT NULL,
  `PAYEE_PARTY_ID` varchar(255) DEFAULT NULL,
  `PAYEE_PARTY_ID_TYPE` varchar(255) DEFAULT NULL,
  `PAYEE_QUOTE_CODE` varchar(255) DEFAULT NULL,
  `PAYER_DFSP_ID` varchar(255) DEFAULT NULL,
  `PAYER_FEE` decimal(38,0) DEFAULT NULL,
  `PAYER_FEE_CURRENCY` varchar(255) DEFAULT NULL,
  `PAYER_PARTY_ID` varchar(255) DEFAULT NULL,
  `PAYER_PARTY_ID_TYPE` varchar(255) DEFAULT NULL,
  `PAYER_QUOTE_CODE` varchar(255) DEFAULT NULL,
  `STARTED_AT` datetime DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `STATUS_DETAIL` varchar(255) DEFAULT NULL,
  `TRANSACTION_ID` varchar(255) DEFAULT NULL,
  `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
  `ERROR_INFORMATION` longtext DEFAULT NULL,
  `BATCH_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_transfers_key` (`WORKFLOW_INSTANCE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `transaction_requests` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AMOUNT` decimal(38,0) DEFAULT NULL,
  `CURRENCY` varchar(255) DEFAULT NULL,
  `COMPLETED_AT` datetime DEFAULT NULL,
  `DIRECTION` varchar(10) DEFAULT NULL,
  `PAYEE_DFSP_ID` varchar(255) DEFAULT NULL,
  `PAYEE_FEE` decimal(38,0) DEFAULT NULL,
  `PAYEE_PARTY_ID` varchar(255) DEFAULT NULL,
  `PAYEE_PARTY_ID_TYPE` varchar(255) DEFAULT NULL,
  `PAYEE_QUOTE_CODE` varchar(255) DEFAULT NULL,
  `PAYER_DFSP_ID` varchar(255) DEFAULT NULL,
  `PAYER_FEE` decimal(38,0) DEFAULT NULL,
  `PAYER_PARTY_ID` varchar(255) DEFAULT NULL,
  `PAYER_PARTY_ID_TYPE` varchar(255) DEFAULT NULL,
  `PAYER_QUOTE_CODE` varchar(255) DEFAULT NULL,
  `STARTED_AT` datetime DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `TRANSACTION_ID` varchar(255) DEFAULT NULL,
  `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
  `AUTH_TYPE` varchar(255) DEFAULT NULL,
  `INITIATOR_TYPE` varchar(255) DEFAULT NULL,
  `SCENARIO` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_transaction_requests_key` (`WORKFLOW_INSTANCE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `variables` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `TIMESTAMP` bigint(20) DEFAULT NULL,
  `VALUE` longtext,
  `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
  `WORKFLOW_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_variables_key` (`WORKFLOW_INSTANCE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `batches` (
     `ID` bigint(20) NOT NULL AUTO_INCREMENT,
     `BATCH_ID` varchar(255) DEFAULT NULL,
     `REQUEST_ID` varchar(255) DEFAULT NULL,
     `REQUEST_FILE` varchar(255) DEFAULT NULL,
     `TOTAL_TRANSACTIONS` bigint(20) DEFAULT NULL,
     `ONGOING` bigint(20) DEFAULT NULL,
     `FAILED` bigint(20) DEFAULT NULL,
     `COMPLETED` bigint(20) DEFAULT NULL,
     `RESULT_FILE` varchar(255) DEFAULT NULL,
     `RESULT_GENERATED_AT` datetime DEFAULT NULL,
     `NOTE` varchar(255) DEFAULT NULL,
     `WORKFLOW_INSTANCE_KEY` bigint(20) DEFAULT NULL,
     `WORKFLOW_KEY` bigint(20) DEFAULT NULL,
     `STARTED_AT` datetime DEFAULT NULL,
     `COMPLETED_AT` datetime DEFAULT NULL,
     PRIMARY KEY (`ID`),
     KEY `idx_batches_key` (`WORKFLOW_INSTANCE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
