CREATE TABLE `errorcode` (
    `ID` bigint(20) NOT NULL AUTO_INCREMENT,
    `TRANSACTION_TYPE` text DEFAULT NULL,
    `ERROR_MESSAGE` text DEFAULT NULL,
    `ERROR_CODE` text DEFAULT NULL,
    `RECOVERABLE` tinyint DEFAULT 0,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;