ALTER TABLE `batches`
    ADD COLUMN `PAYER_FSP` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `batches`
    ADD COLUMN `REGISTERING_INSTITUTION_ID` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `batches`
    ADD COLUMN `CLIENT_CORRELATION_ID` VARCHAR(255) DEFAULT NULL;

ALTER TABLE `batches`
    ADD COLUMN `APPROVED_AMOUNT` BIGINT(20) DEFAULT 0;

ALTER TABLE `batches`
    ADD COLUMN `APPROVED_COUNT` BIGINT(20) DEFAULT 0;
