trigger:
  - main
  - develop

pr:
  - main
  - develop

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    fetchDepth: 0
    fetchTags: true
    displayName: Check out source code

  - task: GetRevision@1
    displayName: "Get Revision"
    inputs:
      VariableName: Revision

  - script: |
      VERSION_TAG=`npm pkg get version | tr -d \"`
      echo "##vso[task.setvariable variable=VERSION_TAG]$VERSION_TAG"
      IMAGE_TAGS="${VERSION_TAG}.$(date '+%Y.%m.%d').$(Revision)"
      echo "##vso[task.setvariable variable=IMAGE_SEMANTIC_HASH]$IMAGE_TAGS"
      if [[ "$(Build.SourceBranchName)" == "main" ]]; then IMAGE_TAGS="$VERSION_TAG,latest"; fi;
      echo Tags: $IMAGE_TAGS
      echo "##vso[task.setvariable variable=IMAGE_TAGS]$IMAGE_TAGS"
    displayName: Generate image tags

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      containerRegistry: "azurecr-oaf"
      command: "login"

  - task: Docker@2
    displayName: Build docker image
    inputs:
      command: build
      buildContext: "$(System.DefaultWorkingDirectory)"
      repository: "oneacrefund/ph-ee-operations-web"
      dockerfile: "$(System.DefaultWorkingDirectory)/Dockerfile"
      containerRegistry: "azurecr-oaf"
      tags: |
        $(IMAGE_TAGS)
  
  - task: Docker@2
    displayName: "Publish image"
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    inputs:
      containerRegistry: "azurecr-oaf"
      repository: "oneacrefund/ph-ee-operations-web"
      command: "push"
      tags: |
        $(IMAGE_TAGS)

  - task: PublishBuildArtifacts@1
    displayName: Publish configuration package
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.SourceBranchName'], 'develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: "ph-ee-operations-web"
      publishLocation: "Container"
