// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export let environment = {
  name: 'dev',
  production: false,
  version: env.npm_package_version + '-dev',
  backend: {
    operations: (window['env']['serverApiUrlOps'] && !window['env']['serverApiUrlOps'].startsWith('$')) ? window['env']['serverApiUrlOps'] : 'http://ops.mifos.gazelle.test/api/v1',
    signatureApiUrl: (window['env']['signatureApiUrl'] && !window['env']['signatureApiUrl'].startsWith('$')) ? window['env']['signatureApiUrl'] : 'http://ops.mifos.gazelle.test/api/v1',
    bulkConnectorOps: (window['env']['bulkConnectorOps'] && !window['env']['bulkConnectorOps'].startsWith('$')) ? window['env']['bulkConnectorOps'] : 'https://ops.mifos.gazelle.test',
    vouchers: (window['env']['serverApiUrlVou'] && !window['env']['serverApiUrlVou'].startsWith('$')) ? window['env']['serverApiUrlVou'] : 'http://ops.mifos.gazelle.test/api/v1',
    voucherCallbackUrl: (window['env']['callbackUrlVou'] && !window['env']['callbackUrlVou'].startsWith('$')) ? window['env']['callbackUrlVou'] : 'https://webhook.site/',
    account: (window['env']['serverApiUrlAct'] && !window['env']['serverApiUrlAct'].startsWith('$')) ? window['env']['serverApiUrlAct'] : 'http://ops.mifos.gazelle.test/api/v1',
    registeringInstituionId: (window['env']['registeringInstitutionId'] && !window['env']['registeringInstitutionId'].startsWith('$')) ? window['env']['registeringInstitutionId'] : 'default',
    g2pPaymentConfigApi: (window['env']['g2pProgramConfigApi'] && !window['env']['g2pProgramConfigApi'].startsWith('$')) ? window['env']['g2pProgramConfigApi'] : 'http://localhost:8084',
  },
  oauth: {
    enabled: (window['env']['oauthEnabled'] && !window['env']['oauthEnabled'].startsWith('$')) ? (window['env']['oauthEnabled'] === 'true') : false,
    type: (window['env']['oauthType'] && !window['env']['oauthType'].startsWith('$')) ? window['env']['oauthType'] : 'keycloak',
    serverUrl: (window['env']['oauthServerUrl'] && !window['env']['oauthServerUrl'].startsWith('$')) ? window['env']['oauthServerUrl'] : 'http://keycloak.mifos.gazelle.test/auth',
    realm: (window['env']['oauthRealm'] && !window['env']['oauthRealm'].startsWith('$')) ? window['env']['oauthRealm'] : 'paymenthub',
    clientId: (window['env']['oauthClientId'] && !window['env']['oauthClientId'].startsWith('$')) ? window['env']['oauthClientId'] : 'opsapp',
    clientSecret: (window['env']['oauthClientSecret'] && !window['env']['oauthClientSecret'].startsWith('$')) ? window['env']['oauthClientSecret'] : '',
    clientUUID: (window['env']['oauthClientUUID'] && !window['env']['oauthClientUUID'].startsWith('$')) ? window['env']['oauthClientUUID'] : '',
    basicAuth: (window['env']['oauthBasicAuth'] && !window['env']['oauthBasicAuth'].startsWith('$')) ? (window['env']['oauthBasicAuth'] === 'true') : true,
    basicAuthToken: (window['env']['oauthBasicAuthToken'] && !window['env']['oauthBasicAuthToken'].startsWith('$')) ? window['env']['oauthBasicAuthToken'] : 'Y2xpZW50Og=='
  },
  jbpm:{
    jbpmApiUrl: (window['env']['jbpmApiUrl'] && !window['env']['jbpmApiUrl'].startsWith('$')) ? window['env']['jbpmApiUrl'] : '',
    containerId: (window['env']['jbpmContainerId'] && !window['env']['jbpmContainerId'].startsWith('$')) ? window['env']['jbpmContainerId'] : '',
    credentials: {
      adminMaker: (window['env']['jbpmCredentialsAdminMaker'] && !window['env']['jbpmCredentialsAdminMaker'].startsWith('$')) ? window['env']['jbpmCredentialsAdminMaker'] : '',
      adminChecker: (window['env']['jbpmCredentialsAdminChecker'] && !window['env']['jbpmCredentialsAdminChecker'].startsWith('$')) ? window['env']['jbpmCredentialsAdminChecker'] : '',
      both: (window['env']['jbpmCredentialsBoth'] && !window['env']['jbpmCredentialsBoth'].startsWith('$')) ? window['env']['jbpmCredentialsBoth'] : ''
    }
  },
  grafana: {
    url: (window['env']['grafanaUrl'] && !window['env']['grafanaUrl'].startsWith('$')) ? window['env']['grafanaUrl'] : '',
  },
  auth: {
    enabled: (window['env']['authEnabled'] && !window['env']['authEnabled'].startsWith('$')) ? (window['env']['authEnabled'] === 'true') : false,
  },
  tenant: (window['env']['platformTenantId'] && !window['env']['platformTenantId'].startsWith('$')) ? window['env']['platformTenantId'] : 'gorilla',
  tenants: (window['env']['platformTenantIds'] && !window['env']['platformTenantIds'].startsWith('$')) ? window['env']['platformTenantIds'] : 'gorilla',
  defaultLanguage: (window['env']['defaultLanguage'] && !window['env']['defaultLanguage'].startsWith('$')) ? window['env']['defaultLanguage'] : 'en',
  supportedLanguages: (window['env']['supportedLanguages'] && !window['env']['supportedLanguages'].startsWith('$')) ? window['env']['supportedLanguages'] : 'en,fr'
};
