// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export let environment = {
  name: 'dev',
  production: false,
  version: env.phee.version + '-dev',
  backend: {
    operations: window['env']['serverApiUrlOps'] || 'http://ops.mifos.gazelle.test/api/v1',
    signatureApiUrl: window['env']['signatureApiUrl'] || 'http://ops.mifos.gazelle.test/api/v1',
    bulkConnectorOps: window['env']['bulkConnectorOps'] || 'https://ops.mifos.gazelle.test',
    vouchers: window['env']['serverApiUrlVou'] || 'http://ops.mifos.gazelle.test/api/v1',
    voucherCallbackUrl: window['env']['callbackUrlVou'] || 'https://webhook.site/',
    account: window['env']['serverApiUrlAct'] || 'http://ops.mifos.gazelle.test/api/v1',
    registeringInstituionId: window['env']['registeringInstitutionId'] || 'default',
  },
  oauth: {
    // For connecting to Mifos X using OAuth2 Authentication change the value to true
    enabled: window['env']['oauthEnabled'] || false,
    type: window['env']['oauthType'] || 'keycloak',
    serverUrl: window['env']['oauthServerUrl'] || 'http://keycloak.mifos.gazelle.test/auth',
    realm: window['env']['oauthRealm'] || 'paymenthub',
    clientId: window['env']['oauthClientId'] || 'opsapp',
    clientSecret: window['env']['oauthClientSecret'] || '',
    basicAuth: window['env']['oauthBasicAuth'] || true,
    basicAuthToken: window['env']['oauthBasicAuthToken'] || 'Y2xpZW50Og=='
  },
  auth: {
    enabled: window['env']['authEnabled'] || false,
  },
  tenant: window['env']['platformTenantId'] || 'gorilla',
  tenants: window['env']['platformTenantIds'] || 'gorilla',
  defaultLanguage: window['env']['defaultLanguage'] || 'en',
  supportedLanguages: window['env']['supportedLanguages'] || ['en', 'fr']
};
